### ISSUE TITLE
Recent LTRs

### ISSUE THREAD

**Issue by aberaslop** [xvazquezc/genome_annotation_with_Maker2#1]
Hi xvazquezc,

Thank you for having your repeat library construction pipeline public, it has been super helpful!

I have one question regarding the protocol: I have been successful in identifying MITEs in my fungal genome, and I have proceeded to identify LTRs. However, when I try to identify candidate elements for recent LTRs, the resulting gff99 file is empty, so I cannot go forward. I assumed that was because perhaps my data-set didn't have any, but I am not sure if this is true (there were not any errors reported). I then moved on to identified older LTRs, which produced a gff85 with data.
At some point in the pipeline, we need to run: 
perl ${DIR_CRL}/cleanRM.pl ${PREFIX}.outinner85.out ${PREFIX}.outinner85.masked > ${PREFIX}.outinner85.unmasked

However, in my case this does not work because i had no 99 output and it seems that cleanRM.pl requires it. So, I am confused as to how to proceed, which are my unmasked and cleaned files?

Thank you so much!

L.

**Comment by xvazquezc** [comment]
mm... it has been quite a while since I ran this but, afaik `cleanRM.pl` does not need the 99 outputs to process the "old LTR". If I'm not wrong, if you follow the protocol, you actually delete them once you have the `LTR99.lib` file.

The `clearRM.pl` detects and _unmasks_ potential nested repeats, outputs the `.unmask` file. Nested repeats may cause misclassification and other issues later on.
Afterwards, `rmshortinner.pl` removes LTR candidates with inner elements <=50 bp as they are most likely to be false LTR. The output is the `.clean` file.

Hope this helps.

**Comment by aberaslop** [comment]
Thank you so much for your prompt answer! You were right, the script is running now. 
Do you agree with my assumption that an empty gff99 suggests a lack of recent LTRs?

Thanks again!
L.

**Comment by xvazquezc** [comment]
I would say so. I mean all programs have their caveats detecting whatever, but it's a fair assumption.

Of course this is also dependent on your assembly.

**Comment by aberaslop** [comment]
Thank you so much for all your help!

**Comment by aberaslop** [comment]
Dear xvazquezc,

I hope 2020 has gone off to a good start! I apologize to contact you out of
the blue again regarding MAKER. In googling my current question I have
seen you have commented on similar issues, so I thought perhaps you could
help me.

I would be very grateful for some advice in training snap. I have followed
the MAKER protocol, but when I use maker2zff, the default parameters are
too strict and I end up without any models. To go on, I have tried to
change -x (max AED to allow) to higher values, but this also doesn't retain
any models. Eventually I had to follow your advice and use -n to use all
models without filtering. My understanding is that the result of no models
may be because of poor evidence, but I have provided MAKER with the
following:

genome=/data1/home/aberas2/genomes/NIGB01.1.fsa

altest=/data1/home/aberas2/evidence/Trichoderma-ESTs.fasta #EST/cDNA
sequence file in fasta format from an alternate organism

altest_gff=/data1/home/aberas2/evidence/PASA_transcript_alignments.gff3
#aligned ESTs or mRNA-seq from an external GFF3 file

protein=/data1/home/aberas2/evidence/five_proteomes.fasta,/data1/home/aberas2/databases/uniprot_sprot_clean.fasta

rmlib=/data1/home/aberas2/genomes/RepeatModeler/AttineDB-families.fa
#provide an organism specific repeat library in f$

repeat_protein=/data1/home/aberas2/maker/data/te_proteins.fasta

snaphmm=/data1/home/aberas2/genomes//maker/NIGB01.hmm

est2genome=0 #infer gene predictions directly from ESTs, 1 = yes, 0 = no

protein2genome=0

always_complete=0

split_hit=3000

single_exon=1 #consider single exon EST evidence when generating
annotations, 1 = yes, 0 = no

single_length=250 #min length required for single exon ESTs if 'single_exon
is enabled'

correct_est_fusion=1

As you can see, I have provided ESTs from closely related fungi obtained
from dbEST in NCBI, PASA results from the transcriptome of a closely
related species (I also have the results of transdecoder, if that helps in
any way), five proteomes from related fungi (from Mycocosm JGI), the
uniprot database, a custom repeat library (thanks for your help there!) and
the te_protein.fasta database provided by MAKER.  Do you think this is not
enough evidence to retain any models when training snap?


Thank you so much in advance. Have a great day!

L.

**Comment by xvazquezc** [comment]
Respect `maker2zff`, it has additional options that may fit better with your own dataset. I'm not completely sure that altest are actually considered as actual EST evidence. I think I read something about it in the Google Groups long time ago. What I know is that they aren't treated as common EST evidence. I have no experience with altest, I either had RNA-seq or my genome had no sequenced closed relatives, in which case I used the `-n` option. You will get a model that will depend on the evidence provided
Before using the `-n` option, I'd try to play with the other parameters, e.g. lowering those using fractions or increasing the minimum AED.

About the files provided, Swissprot is often enough and you probably shouldn't provide anything that comes from predictions without experimental evidence. Note that most, if not all, Mycocosm proteomes are predictions and hard to say if they have gone through any kind of manual curation. To fill the gap between the bulk of the "protein world" and your species, here is where you provide the altest. The altest works in amino acid space like protein2genome and it is a REAL evidence, they are experimentally obtained. You should not use predicted mRNAs or predicted CDS in any of these parameters.

[According to Carson Holt](https://groups.google.com/d/msg/maker-devel/LioXJFF9z-s/90yzcHfQToUJ):
> The only real benefit of altest is to provide evidence of lineage specific
genes for organisms where there are no species in the same branch or
phylum to get protein evidence from.  Since there will only be a handful
of these genes and they can be obtained in any later bootstrap training
steps which will not involve est2genome or protein2genome models. You
should use protein2genome models instead for the initial training and only
use altest for a any bootstrap training or for your final models.

-----
Related to AED and eAED for the scoring of evidence:
https://groups.google.com/d/msg/maker-devel/wtmNRtRa-ko/iC4KTuIitGEJ

Other related notes of interest:
https://groups.google.com/d/msg/maker-devel/OqQVWMM9gZY/-mCM0EKu7SkJ
https://groups.google.com/d/msg/maker-devel/-XE7lKrc8Ig/BV23bfoWBQAJ

**Comment by aberaslop** [comment]
Thank you so much for your answer! I will play around with the other
parameters in maker2zff and see if my models improve. And thanks for the
insights and comments about protein evidence, they are very helpful.
Best,

L.
